# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
#fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: false
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }


fos_rest:
    serializer:
        serialize_null: true

    #  routing_loader:
    #    default_format: json
    #    include_format: false
    body_listener: true
    body_converter:
        enabled: true
    format_listener:
        rules:
            #      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['html', 'json'], fallback_format: json, prefer_extension: false }

    param_fetcher_listener: true
    #  access_denied_listener:
    #    json: true

#      body_converter:
#        enabled: true
    view:
        view_response_listener: true
        formats:
            json: true
            xml: false
            html: false
